Repository googleapis/nodejs-pubsub, pull requests merged in 2019-09, with the labels that each got.

#726 feat: introduces DeadLetterPolicy
  protos/google/pubsub/v1/pubsub.proto
  protos/protos.json
  src/v1/doc/google/pubsub/v1/doc_pubsub.js
  src/v1/subscriber_client.js
  synth.metadata
Labels: cla: yes

#734 feat: update IAM protos
  proto/iam.d.ts
  protos/google/iam/v1/iam_policy.proto
  protos/google/iam/v1/options.proto
  protos/google/iam/v1/policy.proto
  protos/google/type/expr.proto
  samples/system-test/subscriptions.test.js
  samples/system-test/topics.test.js
  system-test/pubsub.ts
Labels: cla: yes

#735 chore: remove conformance tests from .nycrc
  .nycrc
Labels: cla: yes

#730 feat: load protos from JSON, grpc-fallback support
  README.md
  protos/protos.json
  src/v1/doc/google/protobuf/doc_timestamp.js
  src/v1/publisher_client.js
  src/v1/publisher_proto_list.json
  src/v1/subscriber_client.js
  src/v1/subscriber_proto_list.json
  synth.metadata
  synth.py
  test/gapic-v1.js
Labels: cla: yes

#736 fix: update IAM protos
  protos/protos.json
  synth.metadata
Labels: cla: yes

#731 fix: pull projectId from auth client with emulator
  src/pubsub.ts
  test/pubsub.ts
Labels: cla: yes

#729 chore: release 0.32.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#738 docs: update publish sample's rpc timeout settings
  samples/topics.js
Labels: cla: yes

#740 chore(deps): update dependency google-gax to ^1.5.2
  package.json
Labels: cla: yes

#741 chore: release 0.32.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#744 docs(subscription): fix batch options type reference
  src/subscriber.ts
Labels: cla: yes

#746 build: switch to GitHub app for releases
  .github/release-please.yml
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
Labels: cla: yes

#745 chore!: set release level to GA
  .repo-metadata.json
Labels: cla: yes

#748 docs: update README release level to GA
  .github/release-please.yml
  README.md
  synth.metadata
Labels: cla: yes

#755 feat: .d.ts for protos
  .eslintignore
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes

#761 fix: update messaging retry timeout durations
  src/v1/publisher_client_config.json
  src/v1/subscriber_client_config.json
  synth.metadata
Labels: cla: yes

#763 chore: update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes
