Repository googleapis/nodejs-pubsub, pull requests merged in 2019-05, with the labels that each got.

#585 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#584 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#586 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#596 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
  package.json
Labels: automerge, cla: yes

#597 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#598 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#593 build: update build config and doc comments
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  protos/google/pubsub/v1/pubsub.proto
  src/v1/doc/google/pubsub/v1/doc_pubsub.js
  src/v1/publisher_client.js
  src/v1/subscriber_client.js
  synth.metadata
  test/gapic-v1.js
Labels: cla: yes

#600 fix: DEADLINE_EXCEEDED no longer treated as idempotent and retried
  src/v1/doc/google/type/doc_expr.js
  src/v1/publisher_client.js
  src/v1/publisher_client_config.json
  src/v1/subscriber_client.js
  synth.metadata
Labels: cla: yes

#602 test: fix snapshot fixture creation
  test/snapshot.ts
Labels: cla: yes

#605 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v1/publisher_client_config.json
  synth.metadata
Labels: cla: yes

#608 refactor: use core grpc
  package.json
  src/pubsub.ts
  test/index.ts
Labels: cla: yes

#607 refactor(subscriber): message stream retry logic
  src/message-stream.ts
  src/pull-retry.ts
  test/message-stream.ts
  test/pull-retry.ts
Labels: cla: yes

#609 chore: release 0.29.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#611 fix: use typescript import/export for gapics
  src/index.ts
  test/index.ts
  test/pubsub.ts
Labels: cla: yes

#613 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#614 chore: release 0.29.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#616 docs: fix npm link for @google-cloud/pubsub
  CHANGELOG.md
Labels: cla: yes

#618 revert!: remove pullTimeout subscriber option
  src/message-stream.ts
  test/message-stream.ts
Labels: cla: yes

#620 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1/publisher_client.js
  src/v1/subscriber_client.js
  synth.metadata
Labels: cla: yes

#621 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#624 fix(typescript): pin grpc to previous working version
  package.json
Labels: cla: yes

#625 fix(subscription)!: decouple retainAckedMessages from messageRetentionDuration
  src/subscription.ts
  system-test/pubsub.ts
  test/subscription.ts
Labels: cla: yes

#626 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#628 fix: update rpc timeout settings
  src/v1/subscriber_client_config.json
  synth.metadata
Labels: cla: yes

#632 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#633 docs(subscription): mention 100 stream limit
  src/subscription.ts
Labels: cla: yes

#634 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
