Repository googleapis/nodejs-pubsub, pull requests merged in 2019-06, with the labels that each got.

#636 feat: add .repo-metadata.json, start generating README.md
  .cloud-repo-tools.json
  .gitignore
  .readme-partials.yml
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  synth.metadata
Labels: cla: yes

#644 deps: upgrade extend dependency to 3.0.2 due to CVE-2018-16492
  package.json
Labels: cla: yes, kokoro:force-run

#646 fix: update regex to target correct comment
  samples/subscriptions.js
  samples/system-test/topics.test.js
  src/message-queues.ts
  synth.py
Labels: cla: yes

#647 feat: support apiEndpoint override
  src/v1/publisher_client.js
  src/v1/publisher_client_config.json
  src/v1/subscriber_client.js
  synth.metadata
  test/gapic-v1.js
Labels: cla: yes

#648 build: remove unused clang format
  .clang-format
Labels: cla: yes

#630 chore: cleanup resources for system test cases
  system-test/pubsub.ts
Labels: :rotating_light:, cla: yes

#655 docs: update return type in jsdoc for Buffers
  src/v1/doc/google/pubsub/v1/doc_pubsub.js
  src/v1/publisher_client.js
  synth.metadata
Labels: cla: yes

#650 fix(deps): update dependency p-defer to v3
  package.json
  src/message-queues.ts
  system-test/pubsub.ts
Labels: cla: yes

#654 build: enable noImplicitAny in the tsconfig
  package.json
  src/subscription.ts
  tsconfig.json
Labels: cla: yes

#652 docs(subscription): add flow control example
  src/subscription.ts
Labels: cla: yes, kokoro:force-run

#656 docs(subscription): fix duration doc types
  src/pubsub.ts
  src/subscription.ts
Labels: cla: yes

#657 feat(docs): move to new googleapis.dev URL
  .repo-metadata.json
  README.md
Labels: cla: yes

#658 fix(deps)!: use grpc-js instead of grpc extension
  package.json
  src/index.ts
  src/message-queues.ts
  src/message-stream.ts
  src/pubsub.ts
  src/pull-retry.ts
  system-test/pubsub.ts
  test/message-queues.ts
  test/message-stream.ts
  test/pubsub.ts
  test/pull-retry.ts
  test/subscription.ts
  test/topic.ts
Labels: cla: yes

#659 docs(topic): move publish option docs to publisher constructor
  src/publisher.ts
Labels: cla: yes

#660 chore: release 0.30.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#663 build: switch to GitHub magic proxy, for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#665 fix(deps): include missing @grpc/grpc-js dependency
  package.json
Labels: cla: yes

#666 chore: release 0.30.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#670 fix(docs): link to reference docs section on googleapis.dev
  README.md
Labels: cla: yes

#673 docs: improve header linking to other external docs
  .jsdoc.js
  .readme-partials.yml
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes

#677 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: cla: yes
