Repository googleapis/nodejs-pubsub, pull requests merged in 2019-01, with the labels that each got.

#418 docs: sync generated grpc message type docs
  protos/google/pubsub/v1/pubsub.proto
  src/v1/doc/google/pubsub/v1/doc_pubsub.js
  src/v1/publisher_client.js
  src/v1/subscriber_client.js
  synth.metadata
Labels: cla: yes

#388 BREAKING CHANGE: refactor(subscriber): remove unneeded code & utilize typescript
  package.json
  src/connection-pool.ts
  src/histogram.ts
  src/index.ts
  src/lease-manager.ts
  src/message-queues.ts
  src/message-stream.ts
  src/publisher.ts
  src/subscriber.ts
  src/subscription.ts
  src/v1/subscriber_client.js
  system-test/pubsub.ts
  test/connection-pool.ts
  test/histogram.ts
  test/lease-manager.ts
  test/message-queues.ts
  test/message-stream.ts
  test/subscriber.ts
  test/subscription.ts
Labels: cla: yes, semver: major

#419 docs(samples): correct publish retry settings
  samples/topics.js
Labels: cla: yes

#416 build: check broken links in generated docs
  .cloud-repo-tools.json
  .jsdoc.js
  .kokoro/docs.sh
  README.md
  package.json
  src/iam.ts
  src/index.ts
  src/lease-manager.ts
  src/message-queues.ts
  src/message-stream.ts
  src/publisher.ts
  src/subscriber.ts
  src/v1/doc/google/protobuf/doc_timestamp.js
  synth.py
Labels: cla: yes

#425 fix: add getSubscriberStub to synth file
  synth.py
Labels: cla: yes

#429 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  src/v1/subscriber_client.js
  synth.metadata
Labels: cla: yes

#426 refactor(topic): localize publisher to topic instance
  samples/system-test/subscriptions.test.js
  samples/topics.js
  src/index.ts
  src/publisher.ts
  src/topic.ts
  system-test/pubsub.ts
  test/index.ts
  test/publisher.ts
  test/topic.ts
Labels: cla: yes, semver: major

#430 feat(topic): create method for publishing json
  src/topic.ts
  test/topic.ts
Labels: cla: yes

#432 Release @google-cloud/pubsub v0.23.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#434 chore: update year in the license headers
  smoke-test/publisher_smoke_test.js
  src/v1/doc/google/iam/v1/doc_iam_policy.js
  src/v1/doc/google/iam/v1/doc_policy.js
  src/v1/doc/google/protobuf/doc_duration.js
  src/v1/doc/google/protobuf/doc_empty.js
  src/v1/doc/google/protobuf/doc_field_mask.js
  src/v1/doc/google/protobuf/doc_timestamp.js
  src/v1/doc/google/pubsub/v1/doc_pubsub.js
  src/v1/index.js
  src/v1/publisher_client.js
  src/v1/subscriber_client.js
  synth.metadata
  test/gapic-v1.js
Labels: cla: yes

#441 feat(subscription): auto close sub on non-recoverable errors
  src/subscriber.ts
  src/subscription.ts
  test/subscriber.ts
  test/subscription.ts
Labels: cla: yes, semver: minor

#440 refactor: improve subscriber error handling
  src/message-queues.ts
  src/message-stream.ts
  test/message-queues.ts
  test/message-stream.ts
Labels: cla: yes

#439 build: ignore googleapis.com in doc link checker
  .kokoro/docs.sh
Labels: cla: yes

#420 refactor(typescript): noImplicityAny for topic.ts and subscription.ts
  package.json
  proto/pubsub.d.ts
  src/index.ts
  src/subscription.ts
  src/topic.ts
  system-test/pubsub.ts
Labels: cla: yes

#449 fix(sample): factor setTimeout jitter into assertion
  samples/system-test/topics.test.js
Labels: cla: yes

#447 fix(auth): pass project id to gax clients
  src/index.ts
  test/index.ts
Labels: cla: yes

#451 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  package.json
  synth.metadata
Labels: cla: yes

#452 Release @google-cloud/pubsub v0.24.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#454 fix(publisher): unbound max send message size
  src/index.ts
  test/index.ts
Labels: cla: yes

#455 Release @google-cloud/pubsub v0.24.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes
