Repository googleapis/nodejs-pubsub, pull requests merged in 2019-03, with the labels that each got.

#501 refactor(typescript): noImplicitAny for IAM test file
  test/iam.ts
Labels: cla: yes

#508 refactor(typescript):noImplicitAny for lease-manager test file
  test/lease-manager.ts
Labels: cla: yes

#510 refactor(typescript):noImplicitAny for Histogram and Message_queues test file
  test/histogram.ts
  test/message-queues.ts
Labels: cla: yes

#509 docs: update comments on protos
  protos/google/pubsub/v1/pubsub.proto
  src/v1/doc/google/pubsub/v1/doc_pubsub.js
  src/v1/subscriber_client.js
  synth.metadata
Labels: cla: yes

#511 fix(ts): fix getPolicy promise return signature
  src/iam.ts
Labels: cla: yes

#512 fix(docs): ensure docs are not removed by typescript
  src/iam.ts
  src/index.ts
  src/snapshot.ts
  src/subscription.ts
  src/topic.ts
Labels: cla: yes

#515 refactor(typescript): various fixes/refactors to types
  package.json
  proto/iam.d.ts
  src/iam.ts
  src/index.ts
  src/publisher.ts
  src/snapshot.ts
  src/subscription.ts
  src/topic.ts
  system-test/pubsub.ts
  test/iam.ts
  test/index.ts
  test/snapshot.ts
  test/subscription.ts
  test/topic.ts
Labels: cla: yes

#516 fix(typescript): export all the types
  src/iam.ts
  src/index.ts
  src/publisher.ts
  src/pubsub.ts
  src/snapshot.ts
  src/subscription.ts
  src/topic.ts
  test/iam.ts
  test/index.ts
  test/snapshot.ts
  test/subscriber.ts
  test/subscription.ts
  test/topic.ts
Labels: cla: yes

#517 refactor: clean up unused packages
  package.json
  src/iam.ts
  src/message-stream.ts
  src/publisher.ts
  src/pubsub.ts
  src/subscription.ts
  src/topic.ts
  system-test/pubsub.ts
  test/topic.ts
Labels: cla: no

#520 refactor(typescript): noImplicitAny for publisher test file
  test/publisher.ts
Labels: cla: yes

#519 refactor(typescript): noImplicitAny for pubsub system test file
  system-test/pubsub.ts
Labels: cla: yes

#502 refactor(typescript):noImplicitAny for index test file
  src/topic.ts
  test/index.ts
Labels: cla: yes

#521 Release @google-cloud/pubsub v0.27.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#523 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#527 fix(typo): correct typo: recieved => received
  src/subscriber.ts
  test/message-stream.ts
  test/subscriber.ts
Labels: cla: yes

#522 refactor(typescript): noImplicitAny for message-stream test file
  test/message-stream.ts
Labels: cla: yes

#529 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#525 fix(typescript): correct response type of `Subscription.get`
  src/pubsub.ts
  src/subscription.ts
  src/topic.ts
Labels: cla: yes

#528 refactor: type fixes and some light housekeeping
  package.json
  proto/iam.d.ts
  proto/pubsub.d.ts
  src/iam.ts
  src/index.ts
  src/pubsub.ts
  src/snapshot.ts
  src/subscription.ts
  src/topic.ts
  test/snapshot.ts
  test/subscription.ts
  test/topic.ts
Labels: cla: yes

#531 Release @google-cloud/pubsub v0.27.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#533 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#536 test: add missing packages and install test
  package.json
  system-test/fixtures/sample/package.json
  system-test/fixtures/sample/src/index.ts
  system-test/fixtures/sample/tsconfig.json
  system-test/install.ts
Labels: cla: yes

#537 feat(topic): create setMetadata method
  src/index.ts
  src/topic.ts
  test/topic.ts
Labels: cla: yes

#534 refactor(typescript): noImplicitAny for Subscription test file
  src/subscription.ts
  test/histogram.ts
  test/subscription.ts
Labels: cla: yes

#541 fix(typescript): correctly import long
  package.json
  proto/iam.d.ts
  proto/pubsub.d.ts
Labels: cla: yes

#542 refactor: fix/simplify proto gen scripts
  package.json
Labels: cla: yes

#543 testing: set skipLibCheck to false for ts install test
  system-test/fixtures/sample/tsconfig.json
Labels: cla: yes

#544 Release @google-cloud/pubsub v0.28.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#546 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  src/v1/publisher_client.js
  src/v1/subscriber_client.js
  synth.metadata
Labels: cla: yes

#551 build: use per-repo npm publish token
  .kokoro/release/publish.cfg
Labels: cla: yes

#554 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes

#556 feat(subscription): accept pull deadline option
  src/message-stream.ts
  test/message-stream.ts
Labels: cla: yes

#559 feat(subscriber): ordered messages
  protos/google/pubsub/v1/pubsub.proto
  src/v1/doc/google/pubsub/v1/doc_pubsub.js
  src/v1/subscriber_client.js
  synth.metadata
  test/gapic-v1.js
Labels: cla: yes

#560 feat(subscription): ordered messages
  proto/pubsub.d.ts
  src/subscriber.ts
  test/subscriber.ts
Labels: cla: yes

#562 fix: include 'x-goog-request-params' header in requests
  src/v1/publisher_client.js
  src/v1/subscriber_client.js
  synth.metadata
Labels: cla: yes
