Repository googleapis/nodejs-pubsub, pull requests merged in 2019-04, with the labels that each got.

#564 refactor: use execSync for tests
  package.json
  samples/package.json
  samples/system-test/quickstart.test.js
  samples/system-test/subscriptions.test.js
  samples/system-test/topics.test.js
Labels: automerge, cla: yes

#567 chore: switch to include from match
  samples/system-test/subscriptions.test.js
  samples/system-test/topics.test.js
Labels: cla: yes, kokoro:force-run

#566 fix: relax strictEqual to match RegExp
  samples/package.json
  samples/system-test/quickstart.test.js
  samples/system-test/subscriptions.test.js
  samples/system-test/topics.test.js
Labels: cla: yes

#577 chore(docs): formatting updates
  src/v1/doc/google/protobuf/doc_field_mask.js
  src/v1/doc/google/protobuf/doc_timestamp.js
  synth.metadata
Labels: cla: yes

#581 update to .nycrc with --all enabled
  .nycrc
Labels: cla: yes

#580 chore: update formatting for generated code
  src/v1/publisher_client.js
  src/v1/subscriber_client.js
  synth.metadata
Labels: cla: yes
