Repository googleapis/nodejs-pubsub, pull requests merged in 2019-02, with the labels that each got.

#459 test: make smoke test spam less
  smoke-test/publisher_smoke_test.js
Labels: cla: yes

#458 fix(sample): fix retry codes in retry sample code
  samples/topics.js
Labels: cla: yes

#463 test: update code style of smoke test
  smoke-test/publisher_smoke_test.js
  src/v1/publisher_client.js
  src/v1/subscriber_client.js
  synth.metadata
Labels: cla: yes

#464 docs: add lint/fix example to contributing guide
  .github/CONTRIBUTING.md
Labels: cla: yes

#469 docs: make mention of message change in changelog
  CHANGELOG.md
Labels: cla: yes

#470 chore: move CONTRIBUTING.md to root
  CONTRIBUTING.md
Labels: cla: yes

#471 docs: update contributing path in README
  README.md
Labels: cla: yes

#457 refactor(typescript): noImplicityAny for snapshot.ts and publisher.ts
  src/index.ts
  src/publisher.ts
  src/snapshot.ts
  src/subscription.ts
  src/topic.ts
  test/snapshot.ts
Labels: :rotating_light:, cla: yes

#472 build: test using @grpc/grpc-js in CI
  .kokoro/continuous/node8/system-test-grpcjs.cfg
  .kokoro/presubmit/node8/system-test-grpcjs.cfg
Labels: cla: yes

#474 build: create docs test npm scripts
  .kokoro/docs.sh
  package.json
Labels: cla: yes

#479 docs: update links in contrib guide
  CONTRIBUTING.md
Labels: cla: yes

#477 build: use linkinator for docs test
  package.json
Labels: cla: yes

#476 fix: throw on invalid credentials and update retry configs
  src/v1/publisher_client.js
  src/v1/publisher_client_config.json
  src/v1/subscriber_client.js
  src/v1/subscriber_client_config.json
  synth.metadata
Labels: cla: yes

#485 fix: ignore messages that come in after close
  src/lease-manager.ts
  src/subscriber.ts
  system-test/pubsub.ts
  test/lease-manager.ts
  test/subscriber.ts
Labels: cla: yes

#482 refactor(typescript): noImplicityAny for index.ts
  package.json
  src/index.ts
  src/message-queues.ts
  src/message-stream.ts
  src/topic.ts
  system-test/pubsub.ts
Labels: cla: yes

#489 refactor(typescript): noImplicitAny for subscription test file
  test/subscription.ts
Labels: cla: yes

#487 refactor(typescript): noImplicityAny for Topic test file
  test/topic.ts
Labels: automerge, cla: yes

#494 test: fix publishTime issues
  samples/system-test/topics.test.js
Labels: cla: yes

#495 test(samples): correctly handle publishTime value
  samples/system-test/subscriptions.test.js
  samples/system-test/topics.test.js
Labels: cla: yes

#491 Release @google-cloud/pubsub v0.25.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#490 refactor(typescript): noImplicitAny for snapshot and subscriber test file
  test/snapshot.ts
  test/subscriber.ts
Labels: automerge, cla: yes

#498 feat(typescript): ship typescript declaration files
  package.json
Labels: cla: yes

#499 fix(messageStream): remove call to destroy grpc stream
  src/message-stream.ts
  test/message-stream.ts
Labels: cla: yes

#504 feat(subscription): support push config auth methods
  package.json
  proto/pubsub.d.ts
  protos/google/pubsub/v1/pubsub.proto
  src/subscription.ts
  src/v1/doc/google/pubsub/v1/doc_pubsub.js
  synth.metadata
Labels: cla: yes

#503 feat(message): use precise-date for message publish time
  package.json
  src/subscriber.ts
  test/subscriber.ts
Labels: cla: yes

#505 Release @google-cloud/pubsub v0.26.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes
