Repository googleapis/nodejs-pubsub, pull requests merged in 2020-10, with the labels that each got.

#1118 chore: update bucket for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#1120 build(node_library): migrate to Trampoline V2
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
Labels: api: pubsub, automerge: exact, cla: yes, context: full

#1128 feat: update synthtool generation for latest changes
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes

#1122 fix(deps): upgrade google-auth-library
  package.json
Labels: api: pubsub, cla: yes

#1130 build: only check --engine-strict for production deps
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1132 fix: add CANCELLED back to the auto-retry codes for pull subscriptions, for now
  samples/system-test/topics.test.js
  src/pull-retry.ts
Labels: api: pubsub, cla: yes

#1133 chore(deps): update google-auth-library for security fix
  package.json
Labels: cla: yes

#1134 chore: clean up Node.js TOC for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: full

#1140 docs(sample): regional endpoint in publish ordered message sample
  samples/publishOrderedMessage.js
Labels: cla: yes
