Repository googleapis/nodejs-pubsub, pull requests merged in 2020-05, with the labels that each got.

#986 chore: release 1.7.3
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#994 refactor: use grpc from google-gax
  bin/benchwrapper.js
  package.json
  src/index.ts
  src/message-queues.ts
  src/message-stream.ts
  src/publisher/publish-error.ts
  src/pubsub.ts
  src/pull-retry.ts
  test/message-queues.ts
  test/message-stream.ts
  test/publisher/publish-error.ts
  test/pubsub.ts
  test/pull-retry.ts
Labels: cla: yes

#991 fix: regen protos and tests, formatting
  synth.metadata
  test/gapic_publisher_v1.ts
  test/gapic_subscriber_v1.ts
Labels: automerge, cla: yes

#996 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#998 fix: remove unused dependencies
  package.json
Labels: cla: yes

#999 fix(docs): link to correct gaxOptions docs
  src/iam.ts
  src/pubsub.ts
  src/subscription.ts
  src/topic.ts
Labels: cla: yes

#997 docs: removing the experimental tag from dead letter policy related fields
  protos/google/pubsub/v1/pubsub.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#1005 chore: release 2.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: cla: yes

#1012 fix: use any to unblock typescript compilation bug
  test/publisher/message-queues.ts
Labels: cla: yes
