Repository googleapis/nodejs-pubsub, pull requests merged in 2020-11, with the labels that each got.

#1153 fix: node 14+ changes how multiple destroy() calls work
  .github/workflows/ci.yaml
  src/message-stream.ts
  test/message-stream.ts
Labels: api: pubsub, cla: yes

#1147 feat: Enable server side flow control by default with the option to turn it off
  src/message-stream.ts
  src/subscriber.ts
Labels: api: pubsub, automerge, cla: yes

#1142 docs: updated code of conduct (includes update to actions)
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#1148 fix: do not modify options object, use defaultScopes
  .kokoro/trampoline_v2.sh
  package.json
  src/v1/publisher_client.ts
  src/v1/subscriber_client.ts
  synth.metadata
Labels: api: pubsub, cla: yes

#1157 feat: update generator to a new version
  protos/protos.json
  src/v1/publisher_client.ts
  src/v1/subscriber_client.ts
  synth.metadata
Labels: api: pubsub, cla: yes, context: none

#1158 build: stop tracking generated files
  src/pubsub.ts
  synth.metadata
  test/message-queues.ts
Labels: api: pubsub, cla: yes, context: none

#1159 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: pubsub, cla: yes, context: full

#1161 types: fix lint issue
  synth.metadata
  test/message-queues.ts
Labels: api: pubsub, cla: yes, context: none
