Repository googleapis/nodejs-pubsub, pull requests merged in 2020-08, with the labels that each got.

#1079 feat: update to TypeScript 3.8+ to match gax/protobufjs
  package.json
  test/message-stream.ts
  test/pubsub.ts
  test/subscription.ts
Labels: cla: yes

#1060 fix: properly handle non-emulator alternate endpoints for pub/sub
  src/pubsub.ts
  test/pubsub.ts
Labels: cla: yes

#1077 docs: improve document for publish options
  src/publisher/index.ts
  src/publisher/message-batch.ts
  src/pubsub.ts
Labels: cla: yes

#1072 chore: remove experimental warning for ordering keys properties
  protos/google/pubsub/v1/pubsub.proto
  src/v1/publisher_client.ts
  src/v1/subscriber_client.ts
  synth.metadata
Labels: cla: yes, context: full

#1083 build: stop passing credential file when running gcloud container
  .kokoro/populate-secrets.sh
  README.md
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: partial

#1087 fix: make request batching work again
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  src/v1/publisher_client.ts
  src/v1/subscriber_client.ts
  synth.metadata
Labels: cla: yes

#1078 feat: Opentelemetry integration
  package.json
  samples/opentelemetryTracing.js
  samples/package.json
  src/opentelemetry-tracing.ts
  src/publisher/index.ts
  src/subscriber.ts
  test/opentelemetry-tracing.ts
  test/publisher/index.ts
  test/subscriber.ts
Labels: cla: yes

#1085 fix: update minimum gax version to 2.7.0 to fix recent protobuf errors
  package.json
Labels: cla: yes

#1065 docs: add detach subscription link to README
  README.md
  protos/protos.js
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none, do not merge

#1092 chore: start tracking obsolete files
  synth.metadata
Labels: automerge, cla: yes, context: full

#1098 docs(sample): remove repeated code
  samples/publishMessage.js
Labels: api: pubsub, cla: yes

#1100 docs: retry setting docs on sample
  samples/publishWithRetrySettings.js
Labels: cla: yes

#1099 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full
