Repository googleapis/nodejs-pubsub, pull requests merged in 2020-06, with the labels that each got.

#1010 sample: add samples for dead letter topics
  samples/createSubscriptionWithDeadLetterPolicy.js
  samples/removeDeadLetterPolicy.js
  samples/synchronousPullWithDeliveryAttempts.js
  samples/system-test/subscriptions.test.js
  samples/updateDeadLetterPolicy.js
Labels: cla: yes

#1014 feat: re-generated to pick up changes from googleapis
  protos/google/pubsub/v1/pubsub.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/publisher_client.ts
  src/v1/publisher_client_config.json
  synth.metadata
  test/gapic_publisher_v1.ts
Labels: cla: yes, context: partial

#1016 docs: update list of available samples
  README.md
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#1022 feat: move ts target to es2018 from es2016
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v1/publisher_client.ts
  src/v1/subscriber_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#1021 patch: re-generated to pick up changes from googleapis
  protos/google/pubsub/v1/pubsub.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/subscriber_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#1026 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: cla: yes, context: full

#1028 fix: handle fallback option properly
  protos/google/pubsub/v1/pubsub.proto
  src/v1/publisher_client.ts
  src/v1/subscriber_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#1033 fix: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#1035 feat: add flow control settings for StreamingPullRequest to pubsub.proto
  protos/google/pubsub/v1/pubsub.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: full

#1037 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
