Repository googleapis/nodejs-pubsub, pull requests merged in 2020-07, with the labels that each got.

#1042 build: bazel build
  .gitattributes
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#1043 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#1038 feat: Re-export ClientConfig from pubsub.ts in package index.ts
  src/index.ts
Labels: automerge, cla: yes

#1047 chore: add .gitattributes, run synth
  .gitattributes
  synth.metadata
Labels: cla: yes

#1049 build: typo in gitattribute
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#1041 feat: Add support for server-side flow control
  src/message-stream.ts
  src/subscriber.ts
  test/message-stream.ts
  test/subscriber.ts
Labels: cla: yes

#1053 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#1058 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#1059 build: missing closing paren in publish script, delete template for Node 8, add config files for cloud-rad
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#1032 feat: support for detaching subscriptions
  samples/createSubscription.js
  samples/detachSubscription.js
  samples/system-test/subscriptions.test.js
  src/pubsub.ts
  src/subscription.ts
  system-test/pubsub.ts
  test/pubsub.ts
Labels: cla: yes

#1064 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#1066 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  README.md
  samples/README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#1070 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#1073 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full
