Repository googleapis/nodejs-pubsub, pull requests merged in 2021-01, with the labels that each got.

#1172 chore: update license headers
  .jsdoc.js
  protos/protos.d.ts
  protos/protos.js
  src/v1/index.ts
  src/v1/publisher_client.ts
  src/v1/subscriber_client.ts
  synth.metadata
  test/gapic_publisher_v1.ts
  test/gapic_subscriber_v1.ts
Labels: api: pubsub, cla: yes, context: none

#1162 fix(deps): update opentelemetry monorepo to ^0.12.0
  package.json
  src/publisher/index.ts
Labels: api: pubsub, automerge, cla: yes

#1175 feat: adds style enumeration
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: pubsub, cla: yes, context: none

#1188 tests(samples): the acceptable latency for the batch settings test was a bit too low
  samples/system-test/topics.test.js
Labels: api: pubsub, cla: yes, samples

#1184 fix: bind promisify calls for flush() so they have a 'this' value
  src/publisher/index.ts
  test/publisher/index.ts
Labels: api: pubsub, cla: yes

#1199 refactor(nodejs): move build cop to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#1194 fix(samples): Update synchronousPull to avoid INVALID_ARGUMENT error
  samples/synchronousPull.js
Labels: api: pubsub, cla: yes, samples

#1186 samples: fix openTelemetry sample + system test (issue #1185)
  samples/openTelemetryTracing.js
  samples/system-test/openTelemetryTracing.test.js
Labels: api: pubsub, automerge, automerge: exact, cla: yes, samples

#1200 fix: openTelemetry doc fails to generate for #1185
  README.md
  samples/README.md
Labels: api: pubsub, automerge, automerge: exact, cla: yes
