Repository googleapis/nodejs-pubsub, pull requests merged in 2021-06, with the labels that each got.

#1262 samples: add schema samples, typescript sample support
  samples/createAvroSchema.js
  samples/createProtoSchema.js
  samples/createTopicWithSchema.js
  samples/deleteSchema.js
  samples/getSchema.js
  samples/listSchemas.js
  samples/listenForAvroRecords.js
  samples/listenForProtobufMessages.js
  samples/package.json
  samples/publishAvroRecords.js
  samples/publishProtobufMessages.js
  samples/synchronousPull.js
  samples/system-test/fixtures/getSchema-expected.jstest
  samples/system-test/fixtures/getSchema-expected.tstest
  samples/system-test/fixtures/getSchema-fixture.jstest
  samples/system-test/fixtures/getSchema-fixture.tstest
  samples/system-test/fixtures/provinces.avsc
  samples/system-test/fixtures/provinces.proto
  samples/system-test/schema.test.ts
  samples/system-test/typescript.test.ts
  samples/tsconfig.json
  samples/typescript/README.md
  samples/typescript/avro-js.d.ts
  samples/typescript/createAvroSchema.ts
  samples/typescript/createProtoSchema.ts
  samples/typescript/createTopicWithSchema.ts
  samples/typescript/deleteSchema.ts
  samples/typescript/getSchema.ts
  samples/typescript/listSchemas.ts
  samples/typescript/listenForAvroRecords.ts
  samples/typescript/listenForProtobufMessages.ts
  samples/typescript/publishAvroRecords.ts
  samples/typescript/publishProtobufMessages.ts
  samples/typescript/tsconfig.json
  samples/utils/simplifier.js
  src/pubsub.ts
  src/schema.ts
  test/pubsub.ts
  test/schema.ts
Labels: api: pubsub, automerge, cla: yes, samples

#1305 feat: upgrade @opentelemetry/api to version 0.20.0
  package.json
  src/opentelemetry-tracing.ts
  src/publisher/index.ts
  src/subscriber.ts
  test/publisher/index.ts
  test/subscriber.ts
Labels: api: pubsub, automerge, automerge: exact, cla: yes

#1309 chore(nodejs): remove api-extractor dependencies
  package.json
Labels: api: pubsub, automerge, cla: yes

#1311 tests: attempt to make some tests more deterministic
  samples/system-test/schema.test.ts
  samples/system-test/typescript.test.ts
Labels: api: pubsub, cla: yes

#1329 feat: upgrade the opentelemetry api to 1.0.0
  package.json
  samples/package.json
Labels: api: pubsub, automerge, automerge: exact, cla: yes

#1339 chore: delete unused api-extractor dependencies
  package.json
Labels: api: pubsub, cla: yes

#1343 tests: convert sample tests to typescript
  samples/package.json
  samples/system-test/common.ts
  samples/system-test/openTelemetryTracing.test.ts
  samples/system-test/quickstart.test.ts
  samples/system-test/subscriptions.test.ts
  samples/system-test/topics.test.ts
Labels: api: pubsub, cla: yes, samples

#1344 fix(deps): google-gax v2.17.0 with mTLS
  package.json
Labels: api: pubsub, automerge, cla: yes, owlbot:run
