Repository googleapis/nodejs-pubsub, pull requests merged in 2021-08, with the labels that each got.

#1365 chore(nodejs): update client ref docs link in metadata
  .repo-metadata.json
  README.md
Labels: api: pubsub, automerge, cla: yes

#1367 docs: fix 'individual' typo
  src/iam.ts
Labels: cla: yes, automerge, api: pubsub, automerge: exact

#1374 samples: make the comments for publishWithRetrySettings a bit more verbose
  samples/publishWithRetrySettings.js
Labels: cla: yes, automerge, api: pubsub, samples

#1377 fix(deps): google-gax v2.24.1
  package.json
Labels: cla: yes, automerge, api: pubsub

#1371 fix: export publish and subscribe options
  src/index.ts
Labels: cla: yes, automerge, api: pubsub, automerge: exact

#1370 fix: don't require a `data` attribute to be passed when sending a message
  src/publisher/index.ts
  test/publisher/index.ts
Labels: cla: yes, automerge, api: pubsub, automerge: exact
