Repository googleapis/nodejs-pubsub, pull requests merged in 2021-02, with the labels that each got.

#1202 chore: update CODEOWNERS config
  .repo-metadata.json
Labels: api: pubsub, automerge, cla: yes

#1206 feat: update protos from upstream
  .github/CODEOWNERS
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: pubsub, cla: yes, context: partial

#1211 samples: fix sample name for openTelemetryTracing
  samples/openTelemetryTracing.js
Labels: api: pubsub, automerge, cla: yes, samples

#1216 feat: export PublishError
  src/index.ts
Labels: api: pubsub, automerge, automerge: exact, cla: yes
