Repository googleapis/nodejs-pubsub, pull requests merged in 2021-04, with the labels that each got.

#1252 fix: temporarily pin sinon at 10.0.0
  package.json
Labels: api: pubsub, cla: yes

#1245 docs: include `allowExcessMessages` in docs example
  samples/synchronousPullWithLeaseManagement.js
Labels: api: pubsub, cla: yes

#1234 fix: added support for Opentelemetry 0.18
  package.json
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  samples/openTelemetryTracing.js
  samples/package.json
  samples/system-test/openTelemetryTracing.test.js
  src/opentelemetry-tracing.ts
  src/publisher/index.ts
  src/subscriber.ts
  test/opentelemetry-tracing.ts
  test/publisher/index.ts
  test/subscriber.ts
  test/tracing.ts
Labels: api: pubsub, cla: yes

#1256 chore: unpin sinon again
  package.json
Labels: api: pubsub, automerge, cla: yes

#1263 chore: regenerate common templates
  .github/workflows/ci.yaml
  .kokoro/release/publish.cfg
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: full

#1265 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .repo-metadata.json
  owlbot.py
  synth.metadata
  synth.py
Labels: api: pubsub, cla: yes
