Repository googleapis/nodejs-pubsub, pull requests merged in 2022-04, with the labels that each got.

#1505 fix: update grpc.max_metadata_size to 4MiB for exactly-once, and shift ack/modack errors to 'debug' stream channel
  src/message-queues.ts
  src/pubsub.ts
  src/subscriber.ts
  src/subscription.ts
  test/message-queues.ts
  test/pubsub.ts
  test/subscription.ts
Labels: automerge, api: pubsub, size: m

#1518 fix: fix flaky schema and subscription tests
  samples/synchronousPull.js
  samples/synchronousPullWithDeliveryAttempts.js
  samples/synchronousPullWithLeaseManagement.js
  samples/system-test/schema.test.ts
  samples/system-test/subscriptions.test.ts
Labels: api: pubsub, size: l

#1537 tests: make another pass at cleaning up flaky tests
  samples/system-test/schema.test.ts
  samples/system-test/subscriptions.test.ts
Labels: api: pubsub, size: xl

#1522 samples: topic publish() method is deprecated
  samples/publishMessage.js
Labels: api: pubsub, size: xs
